### ISSUE TITLE
Declare a license?

### ISSUE THREAD

**Issue by m7a** [caolan/erlmpd#5]
Hello,

I am considering creating an own MPD player client in Erlang and would like to make use of this library. I checked that it works just fine with some quick testing (even the sticker stuff seemed to work well in my tests after commenting-in the relevant pieces of the code).

Is there any [DFSG-compliant license](https://wiki.debian.org/DFSGLicenses) applicable to the code? Would you mind declaring one for it? I think [Expat](https://directory.fsf.org/wiki/License:Expat) or GPL-3.0 or later would be nice choices but from my point of view, any DFSG-compliant license would do.

Thanks in advance and kind regards,
Linux-Fan, Ma_Sys.ma

**Comment by caolan** [comment]
Now licensed under GPL-3.0 or later: https://github.com/caolan/erlmpd/commit/99485dcf4b5a78f28ce0f7370f4594d56d8bf99a

I'm pleasantly surprised this 15 year old project still works for you. Have fun!

And if/when you release your client please send me a link.
